import 'package:flutter/material.dart';
import 'package:instock/domain/models/theme_preset_id.dart';

const ThemePresetId defaultThemePreset = ThemePresetId.cosmopolitan;

ThemeData themeDataForPreset(ThemePresetId preset) {
  return ThemeData(
    colorScheme: switch (preset) {
      ThemePresetId.cosmopolitan => _cosmopolitanScheme,
      ThemePresetId.pinaColada => _pinaColadaScheme,
      ThemePresetId.whiteRussian => _whiteRussianScheme,
      ThemePresetId.chartreuse => _chartreuseScheme,
      ThemePresetId.blueHawaii => _blueHawaiiScheme,
      ThemePresetId.oldFashioned => _oldFashionedScheme,
    },
    useMaterial3: true,
  );
}

const _cosmopolitanScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFFC2185B),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFF8BBD0),
  onPrimaryContainer: Color(0xFF4A0024),
  secondary: Color(0xFFEC407A),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFFCE4EC),
  onSecondaryContainer: Color(0xFF6A1B3A),
  tertiaryContainer: Color(0xFFB2DFDB),
  onTertiaryContainer: Color(0xFF004D40),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFFFF0F5),
  onSurface: Color(0xFF2A1218),
  onSurfaceVariant: Color(0xFF6B4450),
  surfaceContainerLow: Color(0xFFFFE4EC),
  surfaceContainerHigh: Color(0xFFFFD0DC),
  surfaceContainerHighest: Color(0xFFFFB8CA),
  outlineVariant: Color(0xFFE8B8C6),
  shadow: Color(0xFF000000),
);

const _pinaColadaScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF00897B),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFB2DFDB),
  onPrimaryContainer: Color(0xFF003D36),
  secondary: Color(0xFF26A69A),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE0F2F1),
  onSecondaryContainer: Color(0xFF004D40),
  tertiaryContainer: Color(0xFFFFCCBC),
  onTertiaryContainer: Color(0xFFBF360C),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFFFF8E7),
  onSurface: Color(0xFF1F1A12),
  onSurfaceVariant: Color(0xFF5C5346),
  surfaceContainerLow: Color(0xFFFFF1D6),
  surfaceContainerHigh: Color(0xFFFFE8C2),
  surfaceContainerHighest: Color(0xFFFFDC9E),
  outlineVariant: Color(0xFFE0D2B8),
  shadow: Color(0xFF000000),
);

const _whiteRussianScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF212121),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFE0E0E0),
  onPrimaryContainer: Color(0xFF121212),
  secondary: Color(0xFF616161),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFF5F5F5),
  onSecondaryContainer: Color(0xFF212121),
  tertiaryContainer: Color(0xFFEEEEEE),
  onTertiaryContainer: Color(0xFF424242),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFFAFAFA),
  onSurface: Color(0xFF121212),
  onSurfaceVariant: Color(0xFF616161),
  surfaceContainerLow: Color(0xFFF5F5F5),
  surfaceContainerHigh: Color(0xFFEEEEEE),
  surfaceContainerHighest: Color(0xFFE0E0E0),
  outlineVariant: Color(0xFFBDBDBD),
  shadow: Color(0xFF000000),
);

const _chartreuseScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFD4A017),
  onPrimary: Color(0xFF1A1400),
  primaryContainer: Color(0xFF5C4A0A),
  onPrimaryContainer: Color(0xFFF5E6A3),
  secondary: Color(0xFFC4B56A),
  onSecondary: Color(0xFF1A1400),
  secondaryContainer: Color(0xFF3D3A1F),
  onSecondaryContainer: Color(0xFFE8E0B0),
  tertiaryContainer: Color(0xFF2E5A3C),
  onTertiaryContainer: Color(0xFFC8E6C9),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  surface: Color(0xFF1B4332),
  onSurface: Color(0xFFD8F3DC),
  onSurfaceVariant: Color(0xFF95D5B2),
  surfaceContainerLow: Color(0xFF2D6A4F),
  surfaceContainerHigh: Color(0xFF40916C),
  surfaceContainerHighest: Color(0xFF52B788),
  outlineVariant: Color(0xFF52796F),
  shadow: Color(0xFF000000),
);

const _blueHawaiiScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFFF6E40),
  onPrimary: Color(0xFF1A0500),
  primaryContainer: Color(0xFFBF360C),
  onPrimaryContainer: Color(0xFFFFCCBC),
  secondary: Color(0xFFFFAB91),
  onSecondary: Color(0xFF1A0500),
  secondaryContainer: Color(0xFF5D2E1F),
  onSecondaryContainer: Color(0xFFFFCCBC),
  tertiaryContainer: Color(0xFF00695C),
  onTertiaryContainer: Color(0xFFB2DFDB),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  surface: Color(0xFF0D47A1),
  onSurface: Color(0xFFE3F2FD),
  onSurfaceVariant: Color(0xFF90CAF9),
  surfaceContainerLow: Color(0xFF1565C0),
  surfaceContainerHigh: Color(0xFF1976D2),
  surfaceContainerHighest: Color(0xFF1E88E5),
  outlineVariant: Color(0xFF42A5F5),
  shadow: Color(0xFF000000),
);

const _oldFashionedScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFFFB300),
  onPrimary: Color(0xFF1A1200),
  primaryContainer: Color(0xFF7A5A00),
  onPrimaryContainer: Color(0xFFFFE082),
  secondary: Color(0xFFFFD54F),
  onSecondary: Color(0xFF1A1200),
  secondaryContainer: Color(0xFF4A3B10),
  onSecondaryContainer: Color(0xFFFFE9A8),
  tertiaryContainer: Color(0xFF455A64),
  onTertiaryContainer: Color(0xFFB0BEC5),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  surface: Color(0xFF2C2C2C),
  onSurface: Color(0xFFF5F5F5),
  onSurfaceVariant: Color(0xFFBDBDBD),
  surfaceContainerLow: Color(0xFF383838),
  surfaceContainerHigh: Color(0xFF454545),
  surfaceContainerHighest: Color(0xFF525252),
  outlineVariant: Color(0xFF616161),
  shadow: Color(0xFF000000),
);
